# Generated by Django 3.2.5 on 2021-07-10 13:23

import core.utils
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField()),
                ('file', models.FileField(default='filecontainer/file.pdf', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=core.utils.get_file_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.BooleanField(default=False, help_text='False -> can view, True -> can view and comment')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filepermission', to='core.filecontainer')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='filespermissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
