# Generated by Django 3.2.5 on 2021-07-11 05:53

import core.utils
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepermission',
            name='perm',
        ),
        migrations.RemoveField(
            model_name='filepermission',
            name='users',
        ),
        migrations.AlterField(
            model_name='filecontainer',
            name='file',
            field=models.FileField(default='filecontainer/file.pdf', storage=django.core.files.storage.FileSystemStorage(location='/home/zakir/Desktop/Junior Task/filesharing/media/'), upload_to=core.utils.get_file_path),
        ),
        migrations.CreateModel(
            name='PermType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.BooleanField(default=False, help_text='False -> can view, True -> can view and comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myperm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='filepermission',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='filesshared', to='core.PermType'),
        ),
    ]
