# Generated by Django 3.2.5 on 2021-07-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210711_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontainer',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='filesshared', to='core.PermType'),
        ),
        migrations.DeleteModel(
            name='FilePermission',
        ),
    ]
